### ISSUE TITLE
Open Collar Core not allowing multiple Collar devices

### ISSUE THREAD

**Issue by Celestrea** [OpenCollarTeam/OpenCollar#77] opened 2017-12-21 03:59 UTC
What version of OpenCollar are you using? 7.0

What behavior did you expect? To be able to use two separate OC scripted devices congruently

What behavior did you see instead? It gives an error statement and removed the most recently added item. I have removed RLV on the offending device but it continues to remove the most recent device and I would like to use rlv options on both devices.

What steps does someone need to take to reproduce the problem?Wear two open collar scripted items

Ok, now that the preliminaries are over this is mostly a suggestion. I sell OC clit rings and most people like to use their collar and a scripted clit ring at the same time. Not to mention there are many times that I see where someone will have a special collar for their owner and a separate collar (maybe with lesser functionality) for play partners. In either case two separate OC scripted devices cannot be used together. If there is a way around this (yes I tried to turn off RLV on one of the devices) or if perhaps a 2nd collar version that can be used in conjunction with the official full version.  In many cases an invisi collar may work but in the case of the clit ring they normally want both shown and attachment points on the leash to come from either or both devices.

**Comment by CorwinDavidson** [comment] 2017-12-21 07:52
This is a duplicate of Issue #51

**Comment by nirea** [comment] 2017-12-24 17:16
Going to close this in favor of #51.  I'll make a note over there to read this ticket too.

**Closed by nirea** 2017-12-24 17:16 UTC
