### ISSUE TITLE
Old Camera maxdist is not cleared when changing maxdist

### ISSUE THREAD

**Issue by marrmist** [OpenCollarTeam/OpenCollar#491] opened 2021-03-05 00:01 UTC
What version of OpenCollar are you using?
8.0.4000

What behavior did you expect?
When setcam_avdistmax restriction is active, and the configured camera distance limit is changed, the existing restriction should be updated.

What behavior did you see instead?
The existing restriction seems to be forgotten by the collar and left active.

What steps does someone need to take to reproduce the problem?
- Enable camera distance limit
- Change value of camera distance limit
- Check RLVa restrictions (I see old limit)
- Lift the restriction
- Check RLVa restrictions (I still see old limit)
- Re-apply the restriction
- Check RLVa restrictions (I see both old limit and new limit)

Note: I did not test the other numeric-configurable RLV restrictions (camera min dist, and blur amount) but I would guess that they suffer from the same bug.

**Comment by zontreck** [comment] 2021-03-05 00:02
This issue is known.

**Comment by zontreck** [comment] 2021-03-05 00:02
Marking as duplicate of #432

**Comment by zontreck** [comment] 2021-03-05 00:03
Any further discussion on this issue should be continued in #432  - Thank you!

**Closed by zontreck** 2021-03-05 00:02 UTC
