### ISSUE TITLE
RLV restrictions blocking Collar commands too.

### ISSUE THREAD

**Issue by Surssin** [OpenCollarTeam/OpenCollar#709] opened 2021-11-24 16:27 UTC
OpenCollar version 8.2.1000 

It seems that the RLV restrictions such as blocking sit or add attachments blocks the collar too. Neither outfits nor the RLV folder can add/remove attachments unless it is cleared. Same with force sitting. It has to be removed before my owner can force sit me.

Not much more to it really. My owner can't use my collar to sit me or dress me unless the restrictions are cleared.

Side note: as I think someone else noted, the strict sit command is not cleared even though it is unchecked. I have had to relog to clear it after it is turned off.

**Comment by Surssin** [comment] 2021-11-25 01:49
Expanded thought:
Total noob scriptor here so I know full well it's likely not this easy, but here's a bad idea anyway.

I wonder if it could be fixed by the collar detecting that the restriction is on. Then if it is, it would turn it off, do what it's gonna do, then turn it back on. Could potentially add a "state" that's set when say add attach is blocked, and then it detects that state and takes an extra step. Or some other method to somehow detect that the restriction is active so that it knows to do something like this sequence;

turn off block add/remove attachments.
Sleep for a fraction of a second (if it needs a moment for it to clear)
add/remove clothing/attachments that it has been commanded to.
sleep/delay for a moment again to give the outfit time to do do
turn the block back on.

It may not work at all or be even close to that easy, but it's all my poor skills can think of.

**Comment by SilkieSabra** [comment] 2021-11-26 23:40
The issue is adding attachments.  As you have realized, If a RLV block on adding attachments is enforced, it has to be cleared before you can add attachments.  

Not sure why blocking sit would do this so please double check by checking what restrictions are enforced when sit is blocked.  

Strict Sit is a separate issue.  There are three issues here. I've marked this as a feature request based on your expanded thoughts,  and a separate issue for Strict Sit would be helpful.

**Comment by Surssin** [comment] 2021-11-27 03:53
It seems that the listed restriction is just "sit" and "unsit". SitTP is blocked when my leash is held, but it didn't seem to matter if my leash was held or not.

**Comment by Medea-Destiny** [comment] 2021-12-07 19:22
In 8.2 we implemented RLV_CMD_OVERRIDE which is a way to enable one-shot RLV commands triggered by the collar to temporarily override restrictions, so that the actions of an owner are not restricted by restrictions intended to restrict the behaviour of the wearer.

As per current version, this new function is only used for the UNSIT button. Now the capability is there we can, over time, extend it to other areas of the collar such as adding attachments when dressing is locked or force sitting when sit is restricted. 

As such this feature is already in place, and using the function for a wider range of collar operations is the plan, but obviously it'll take time. @Surssin does this address your issue? Please respond if you have any further comment on the issue, otherwise I believe this can be closed as resolved / in progress.

**Comment by Surssin** [comment] 2021-12-08 02:15
@Medea-Destiny I think it can be marked as such. I know such things can be hard to pin down and make work as intended, so if it's in the pipeline, that's good enough for me. Looking forward to when it's functional and live!

**Comment by Surssin** [comment] 2021-12-08 04:38
Hm, with one thought that I don't know if it can be done or not; I know exceptions allow for things like IMing an owner even when something else blocks IMs. I don't know if that could be done for this too. My thinking is if an RLV trap, or just some other piece of gear, is blocking things, the exceptions or that override command line would still allow an owner to do things with their sub. A LOT harder to pull off, I have no doubt, but maybe eventually?

**Comment by Medea-Destiny** [comment] 2021-12-09 10:25
@Surssin Thanks for the reply. RLV offers limited scope for one object to override the restrictions put in place by another object. Where something is done by an RLV trap via the built-in relay we can override it because ultimately it's the collar placing the restriction as a relay for the trap, but otherwise this isn't really something possible to do.

**Comment by Surssin** [comment] 2021-12-09 14:38
Makes total sense. Oh well. Was a thought. Thanks for all you do with it.

**Closed** 2021-12-10 18:14 UTC
Labels: Feature, Fixed
