### ISSUE TITLE
Access deneid because you are out of range to sim owner

### ISSUE THREAD

**Issue by AlexaFinch** [OpenCollarTeam/OpenCollar#565] opened 2021-05-23 22:49 UTC
What version of OpenCollar are you using?
I don't but visitors to my sim do. Various versions

What behavior did you expect?
I expect to not be spammed by people's restraints when they visit my sim. I get offline messages too. I get messages even if I am in another sim. 

What behavior did you see instead?
SPAM I get messaged every 15 seconds in some cases. Blocking channel 1 is not an option as gags send on that channel. I use a spy device to hear what gagged people actually say. 

What steps does someone need to take to reproduce the problem?
The problem stopped from one person when they did the following.
 I added "a friend" as trusted.. I don't know if she has disabled the limit range.. probably it was that

**Comment by lavababii** [comment] 2021-06-02 06:30
Same here.
If this annoyance isn't fixed soon I'll have to ban open collar from my places.

**Comment by AlexaFinch** [comment] 2021-06-12 17:27
I have asked some individuals to not use OC at my sim. I'm reluctant to do an outright ban. OC is all some people can afford. This is highly irritating. I am going to send a group notice requesting people to not use OC. This is becoming a major issue that needs immediate attention.

**Comment by lavababii** [comment] 2021-06-12 17:35
I've checked the source code and it IS ACTUALLY coming from the open collar relay thingie. However, problem got less in the past days, but I am evaluating options to detect OpenCollar RLV relays. Coders, please this half-baked idea from your code. Do *NOT* use llGetOwneyKey() of RLV clients. It's simple as that.

**Comment by khee44** [comment] 2021-06-12 20:19
I have been experiencing this message from users on my sim as well. It seems to be caused by an unfortunate interaction between the relay and the collar's authorisation API.  If the relay is put in "ask" mode, then when a device tries to restrain the wearer,  The oc_relay script tries to check if the device's owner is authorised to do so.  It does this by sending an AUTH_REQUEST message to the link set. This is picked up by the oc_api script.  The CalcAuth function in this script runs through a list of checks to try and decide if this person is authorised or not - and if they all fail, it results in a NOTIFY message being sent to the link set with the "out of range" message. This message is picked by by the oc_dialog script, which sends it to the person who was being checked - the device owner (usually the sim owner) in this case, thus spamming them annoyingly.

Obviously the relay should not be trying to authorise things based on the restricting device's owner.  Ideally, The relay should be checking things based on the person using the device at the time, not the device's owner, However there is no way to do this reliably.  There are unofficial extensions to the relay protocol which try to solve this problem, but not all relays and not all devices support them, so they can't be relied on. Therefore I think this function should be dropped from the relay - 'ask' mode should always just prompt the wearer, regardless of who the person trapping them is. 

It certainly shouldn't spam the device owner with messages.

**Comment by khee44** [comment] 2021-06-12 21:34
I have also been seeing these "Access Denied because you are out of range" messages from users on my sim when I am offline. The code is difficult to untangle, to work out what might be going on here. The "out of range" message seems to be generated in oc_api in the CalcAuth function.  

At first I thought it was being triggered by the oc_relay when the relay is in ask mode, as it sends an AUTH_REQUEST message to oc_api to check if the owner of the restraining device is authorised.  However, this results in CalcAuth being called with iVerbose set to FALSE which should mean it does NOT generate the notify message. 

The oc_api script only calls CalcAuth with iVerbose set to TRUE in response to a CMD_ZERO message.  The oc_relay script does send a CMD_ZERO messsage, but only when the collar is in public mode and someone tries to change the relay settings; and in this case it seems that the correct "someone" is checked rather than the sim/device owner, so I remain in the dark about how exactly these messages end up coming to the sim owner.

So far I haven't been able to reproduce the issue while testing, I only see it as IMs arriving while I'm offline. It is very frustrating.

**Comment by Pingout** [comment] 2021-06-13 15:35
I'm pretty sure this issue has been resolved and will be in the Q2 Release (Version 8.0.6)
https://github.com/OpenCollarTeam/OpenCollar/pull/542
https://github.com/OpenCollarTeam/OpenCollar/blob/features-2021-q2/src/collar/oc_api.lsl

**Comment by SilkieSabra** [comment] 2021-06-13 19:10
This is a pretty urgent fix, so between now and the next release, download the version of oc_api from the features branch (Ping posted it) and tell people to swap out that script, if it gets unbearable.  I think this is bothering enough people that there should be a patch release; however we are hoping to get the next release out before the end of June.

**Closed by SilkieSabra** 2021-06-13 19:10 UTC
