### ISSUE TITLE
Titler particle menu should re-appear after use

### ISSUE THREAD

**Issue by nirea** [OpenCollarTeam/OpenCollar#94] opened 2018-01-08 06:35 UTC
What version of OpenCollar are you using?
Mano Nevadan's new titler feature

What behavior did you expect?
After clicking the (off) button, I should get the menu back.

What behavior did you see instead?
No menu.

What steps does someone need to take to reproduce the problem?
Install the titler version from Mano's pull request.  Say *particle.  Click Select.  Turn on an overhead particle.  Click Select again to turn off the particle.

**Comment by zontreck** [comment] 2019-07-07 08:58
This does not appear to have been fixed in 7.2 RC, will fix prior to full release

**Comment by zontreck** [comment] 2019-07-10 10:22
Could not reproduce. Marking as fixed; Closing issue

**Closed** 2019-07-10 10:24 UTC
Labels: Fixed
