### ISSUE TITLE
Run time error - Stack-Heap Collision 

### ISSUE THREAD

**Issue by ZennyJewell** [OpenCollarTeam/OpenCollar#316] opened 2020-04-24 09:47 UTC
What version of OpenCollar are you using?
7.4
What behavior did you expect?
open folder in menu 
What behavior did you see instead?
 [script:oc_folders] Script run-time error  and  Stack-Heap Collision
What steps does someone need to take to reproduce the problem?
I was opening the clothes folder and get this message. 

After that I detached the OC Periculum and attached it again. and got the same:
[02:40] Periculum - Control Septum / Gold (Open Collar): Periculum - Control Septum / Gold (Open Collar) [script:oc_folders] Script run-time error
[02:40] Periculum - Control Septum / Gold (Open Collar): Stack-Heap Collision
[02:40] Periculum - Control Septum / Gold (Open Collar): RLV ready!

**Comment by zontreck** [comment] 2020-04-24 10:41
This is a known bug. However this is most commonly caused by long folder names, or a ton of folders in #RLV.

**Comment by zontreck** [comment] 2020-04-24 10:42
How many folders do you have in #RLV, and also how many digits are the folder names?

**Comment by zontreck** [comment] 2020-04-24 10:44
Help wanted tag has been added incase anyone feels like rewriting oc_folders while waiting for more information from @ZennyJewell

**Comment by ZennyJewell** [comment] 2020-04-24 11:35
To give an idea of my RLV inventory, yes it has a lot folders....  but pretty well organized into sub folders. Folder names can be an issue as they are taken over from the creators of the items. Digits can be too much. Let me show you some pics I added.
![Knipsel](https://user-images.githubusercontent.com/41748250/80208095-c54d8c00-862f-11ea-8333-5692c4737ab0.JPG)
![Knipsel2](https://user-images.githubusercontent.com/41748250/80208097-c5e62280-862f-11ea-9de8-6e41ab65de0e.JPG)
![Knipsel3](https://user-images.githubusercontent.com/41748250/80208099-c67eb900-862f-11ea-83cc-0705df1cea67.JPG)
![Knipsel4](https://user-images.githubusercontent.com/41748250/80208100-c67eb900-862f-11ea-98af-550c9d9a7444.JPG)

As I am not wearing a collar myself, but my sub does, I had to wear one myself and try. Until version 7.1 it was no issue, we updated to 7.4 and now it is.

**Comment by zontreck** [comment] 2020-04-24 17:49
Some of those folder names are too long

**Comment by SimplyNemz** [comment] 2020-04-26 04:39
I'd also recommend removing any special characters ( *:[]:^-, etc). Not sure if they will cause conflict with OC script, but they often do with other #RLV scripts.

**Comment by ZennyJewell** [comment] 2020-04-26 09:20
> Some of those folder names are too long

It might be now, I didn't have any issues before with them. As far I know a button can handle not more than 24 digits. in older huds it seem that the rest is capped.

**Comment by ZennyJewell** [comment] 2020-04-26 09:23
> I'd also recommend removing any special characters ( *:[]:^-, etc). Not sure if they will cause conflict with OC script, but they often do with other #RLV scripts.
They don't conflict so far, but I am working on that as it makes the folder names longer than needed.

**Comment by SilkieSabra** [comment] 2020-04-26 12:21
Do you have all this stuff in #RLV because you are using CTS Wardrobe?  It uses a web interface so doesn't run into the same script caps as objects using LSL.  This question is for information / support purposes.  
Some people have succeeded by making fewer top folders, I see places where you could group related items with some intermediate folders.  I hope someone volunteers as this issue affects a  small but significant number of users.

**Comment by ZennyJewell** [comment] 2020-04-26 13:00
Hi @SilkieSabra ,  Myself I use CTS wardrobe now indeed.  But my girl has a collar, updated to the latest version. It didn't give any issue with the collar until the update, nor with the OpenCollar Menu HUD (for OC v6.0) - 2.1 or OpenCollar Remote hud.  Somehow it is now,  But we are working on the length of her folder names and hope that will help. (I was trying a collar to see if it was just collar related or script related, but we got both the same errors).

**Comment by zontreck** [comment] 2020-06-04 03:30
Closing this issue as: Not a bug; Limitation of Second Life

**Closed** 2020-06-04 03:30 UTC
