### ISSUE TITLE
OpenCollar 8 Leash handing leash vs pull not showing visible leash

### ISSUE THREAD

**Issue by Saraminka** [OpenCollarTeam/OpenCollar#476] opened 2021-01-24 10:17 UTC
What version of OpenCollar are you using?
7.5, and then upgraded to OpenCollar 8.0.1000 

What behavior did you expect?
When I hand my leash to someone to see the visible leash from me to them just like when a trusted user or owner pulls me.

What behavior did you see instead?
The leash was never visible when I initiated the leashing, if owner pulled me the leash was always visible. Tested this twice, had her drop the leash, I initiated it, not visible, she dropped the leash, and pulled the leash was visible.

What steps does someone need to take to reproduce the problem?
Have the wearer of the collar offer their leash to someone, if it behaves the same as mine, it won't be visible. Have the owner pull them, it is visible.

**Comment by zontreck** [comment] 2021-01-24 10:19
Please do not post issues that can be resolved by first asking in the support group for basic troubleshooting steps

**Comment by zontreck** [comment] 2021-01-24 10:20
Please see the Leash->Configure menu

**Closed by zontreck** 2021-01-24 10:19 UTC

**Comment by zontreck** [comment] 2021-01-24 10:40
[RESOLVED] User error: User was initiating follow instead of leash

<h2>
***NOT A BUG***</h2>

**Comment by Saraminka** [comment] 2021-01-24 10:50
I did ask in the support channel, they said go here. Sorry it was a Minka issue not a bug. =]
