### ISSUE TITLE
Detach bug when not OwnSelf

### ISSUE THREAD

**Issue by avelluna** [OpenCollarTeam/OpenCollar#185] opened 2018-12-03 19:54 UTC
What version of OpenCollar are you using?

What behavior did you expect?

What behavior did you see instead?

What steps does someone need to take to reproduce the problem?

**Comment by zontreck** [comment] 2019-02-09 18:00
I need more information to reproduce this issue since I followed the provided steps and the detach menu works

**Comment by zontreck** [comment] 2019-03-25 09:46
Closing this as cannot reproduce.

**Closed by zontreck** 2019-03-25 09:46 UTC
Labels: More Info Needed
