### ISSUE TITLE
Strict Leash Broken?

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#474] opened 2021-01-16 18:01 UTC
OpenCollar V8 RC3:

Strict setting in Leash menu, when pressed does not appear to be activated and is not enforcing any restrictions.  This was confirmed by me on my own modified collar (I have some different wearer access settings than most) and two others in the OpenCollar group.

**Comment by 15018342** [comment] 2021-01-16 18:07
I'm one of the people who confirmed that strict is not working.

I'm also seeing that "turn" is behaving the same. The button does not change when clicked, and I do not turn to face the leash holder when pulled by the leash.

**Comment by Steele620** [comment] 2021-01-16 18:14
I was the one who brought this subject up, and I will have to add to it about the Turn and Strict, neither work. I have attempted to turn both on, and they remain unchecked or filled in.

**Comment by zontreck** [comment] 2021-01-16 18:22
This has already been reported and there is already one or two tickets about this

**Comment by zontreck** [comment] 2021-01-16 18:24
Duplicate of #429

**Comment by SilkieSabra** [comment] 2021-01-16 18:24
Thanks, was not aware of it, we merge these now?

**Closed** 2021-01-16 18:24 UTC
