### ISSUE TITLE
Feature Request - Provide a method where Collar can Digest LMs placed in Collar

### ISSUE THREAD

**Issue by Attitum** [OpenCollarTeam/OpenCollar#109] opened 2018-01-13 04:01 UTC
Back in the day the last version to support this was 3.971 and i have missed it every since.
When this feature was replaced they created the bookmarks feature but never created an ability for it to support exceptions so it was basically a useless features as it took longer to goto an LM from collar then it did from inventory so bookmarks was never used.

**Comment by CorwinDavidson** [comment] 2018-01-13 05:22
Not sure what you mean by exceptions unless you are referring to RLV exceptions for permissions

**Comment by IsabeauConnaught** [comment] 2018-01-13 16:27
well, for me its way faster to type [prefix]tp "bookmark name" in local than finding LM in inv. So I shouldnt call bookmarks useless

**Comment by nirea** [comment] 2018-01-13 23:48
@xEmpiricalx could you explain more what you mean by exceptions?  I don't understand.

**Comment by IsabeauConnaught** [comment] 2018-01-14 07:44
@nirea only exceptions i can think about are ones set for owners (including wearer if vanilla) and trusted. as bookmarks are all about tp, exceptions and restrictions for use of them are covered with lure and refuse tp, right?

**Comment by xEmpiricalx** [comment] 2018-01-16 03:47
In response to clarity, if you back to say version 3.971, in those days you would ADD Landmarks to a collar lets say  Place  01, 02, 03. As a result of this like IsabeauConnaught mentioned you can type  [prefix]tp  01, or 02, or 03 to goto 1 of those places, this works because the Landmarks are in the collar.   Also lets imagine your into RLV and your owner restricted tplm, tploc, tplure.   Because your now restricted when you click in your inventory on an Landmark you get DENIED.   But if you typed [prefix]tp  01, or 02, or 03 meaning one of the places that was in your collar you can tp to that spot.  You can think of this as a whitelist method to control where a sub can travel, it used to be in the collars and was taken out.  The reason i bring up EXCEPTIONS is because the new bookmarks methods has no EXCEPTIONS for travel and this method does not work when restricted tplm, tploc, tplure.  Bookmarks I gather was designed to replace the collar digesting Landmarks but was never feature complete.

**Comment by IsabeauConnaught** [comment] 2018-01-16 16:59
oh.....i see your point now. stray unchecked in restriction, you want bookmarks to be excepted from this. sorry, i had to try with my alt and find out myself....

**Comment by SilkieSabra** [comment] 2018-05-07 17:08
I believe that was considered a loophole on teleport restrictions with the old tp to landmark; the chat command [prefix] tp [bookmarkname] still works as before but it no longer slips past tp restrictions.  This is a discussion point whether it should be used in this way.

**Comment by Medea-Destiny** [comment] 2023-08-02 22:07
RLV_COMMAND_OVERRIDE feature introduced in 8.2 could be used to allow owner issued bookmark teleports to override restrictions.

**Comment by Medea-Destiny** [comment] 2023-08-02 22:35
Closing as #317 covers the same ground and is clearer.

**Closed by Medea-Destiny** 2023-08-02 22:35 UTC
Labels: Feature
