### ISSUE TITLE
OC conflict with Firestorm AO

### ISSUE THREAD

**Issue by Catspawgat** [OpenCollarTeam/OpenCollar#47] opened 2017-12-06 04:58 UTC
What version of OpenCollar are you using?
7.0 Beta 3
What behavior did you expect?
Stop RLV Poses
What behavior did you see instead?
Found another issue... When using the RLV Poses, and you stop them, it activates the Firestorm builtin AO...Example, if you have dances in the firestorm builtin AO and use the collar poses. When you stop them, the Firestorm AO auto starts and puts the wearer into a dance...
What steps does someone need to take to reproduce the problem?
1. Activate collar menu
2. Click Animations --> Pose
3. Set wearer in any pose.
4. Choose STOP (to stop the pose)
5. Firestorm AO auto checks itself and wearer starts the first animation in their built-in AO

**Comment by Catspawgat** [comment] 2017-12-06 05:07
I did some more testing on this issue
Once you stop the Pose, and Firestorm AO activates, you can go back to the Animations menu, Click AO Off and it turns the FS AO Off. This is good but FS AO should not auto start to begin with IMO

**Comment by SatomiAhn** [comment] 2017-12-06 07:27
If you do not use Firestorm builtin AO, you need to disable OpenCollar integration in Firestorm settings, then all will be fine.

If do use it, then I suppose it is the intended behavior (AO stops and resumes when a collar pose starts or stops).

**Comment by nirea** [comment] 2017-12-07 00:46
Satomi do you have a documentation link for how to disable OC integration in the Firestorm settings?

**Comment by SatomiAhn** [comment] 2017-12-07 22:06
It's easier for me to describe how to do so than looking for some existing documentation:
In firestorm:
- hit ctrl+P (i.e. go to preferences)
- go to Firestorm tab
- go to Avatar sub-tab
- uncheck "Allow OpenCollar protocol to enable or disable built in AO" (at the bottom of the dialog)

Alternatively, it is in debug settings. The key is BridgeIntergrationOC (set it to FALSE).

**Comment by nirea** [comment] 2017-12-08 17:43
Thank you Satomi!

@SilkieSabra, could you document this in our wiki page on the AO?

**Comment by SilkieSabra** [comment] 2017-12-11 16:44
I put this on the Animations menu, are we putting out a Sub AO? there's no documentation for that yet.

**Comment by Catspawgat** [comment] 2017-12-12 20:32
Sorry for the delay, this worked like a charm, thank you

**Comment by nirea** [comment] 2017-12-13 16:32
@SilkieSabra We'll do the sub AO eventually but not yet.

Closing this ticket.

**Closed by nirea** 2017-12-13 16:32 UTC
