### ISSUE TITLE
Setgroup not clearing when group is unchecked

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#566] opened 2021-05-25 00:36 UTC
In V8.0.5, several users have reported that Group Access was checked, then unchecked, but @setgroup=0 was not cleared.  It may be intermittent as at least one person was able to clear it by rechecking group, then unchecking it again.  Others have had to reset the collar to clear it.

**Comment by MNight75** [comment] 2021-05-25 00:58
The person reporting it to me had just updated a brightcollar to the newest OC, doesn't use group and found group restrictions set that were not cleared by checking and unchecking group. 
Additionally a second person I helped with the issue tried the same thing and also failed, until the removed and replaced the collar. Then and only then would clicking and unclicking group clear the restriction.

**Comment by Medea-Destiny** [comment] 2021-06-25 23:01
I have a fix for this which I will be appearing in a pull soon. Basically the problem was that the restriction was being set if group key was not NULL_KEY, but group key gets set to "" if it's NULL_KEY so it needed to be set if group key was not "" instead. 

It has been suggested to me that an additional aspect to this is that the group access option can be set when there is no active group. The fix as above resolves the setgroup issue, but retains the misleading presentation of group access being set when there is no group value stored. To resolve this, my edit will disallow setting group access if there is no current group set.  Any comments/disagreements about this?

**Comment by Medea-Destiny** [comment] 2021-06-27 23:46
Fix provided in https://github.com/OpenCollarTeam/OpenCollar/tree/Medea-4.1-1

**Comment by SilkieSabra** [comment] 2021-07-05 13:14
I think that makes perfect sense (late response),

**Comment by Trinkitz** [comment] 2021-07-05 13:26
This seems to work as intended. Typo in the notice I receive in local chat when trying to set group access with no group active: " Ping Designs: roup access can't be set while no group is active."

**Comment by Medea-Destiny** [comment] 2021-07-16 18:07
Leaving this open to deal with typo issues for 8.2

**Closed** 2021-11-05 00:57 UTC
Labels: Bug
