### ISSUE TITLE
Unable to remove a bookmark after collar script reset

### ISSUE THREAD

**Issue by Trotmistwalker** [OpenCollarTeam/OpenCollar#612] opened 2021-07-15 07:03 UTC
What version of OpenCollar are you using?
8.1
What behavior did you expect?
when the remove button is pressed under bookmarks there should be a list of possible bookmarks to remove.
What behavior did you see instead?
Instead what appears are two blank buttons
What steps does someone need to take to reproduce the problem?
From what I can tell do a script reset on an 8.1 collar with bookmarks on the .bookmarks note card. select bookmarks and remove and see if there are options displayed.

**Comment by Trotmistwalker** [comment] 2021-07-15 07:30
On further testing, if there are bookmarks saved in the collar and not on the .bookmarks notecard they will display as an option to be removed. Remove bookmarks however does not pull any of the bookmarks from the .bookmarks notecard as an option to remove.

**Comment by Medea-Destiny** [comment] 2021-07-15 14:52
This is correct. Scripts cannot edit notecards, so it is impossible for the script to delete bookmarks saved in the notecard. If you want to delete those, delete them manually from the  notecard. 

@Trotmistwalker Please reply letting me know if this clarifies things and fits your observations and if so I'll close the issue.

**Comment by SilkieSabra** [comment] 2021-07-15 15:18
So, if the bookmarks are saved in .bookmarks they should appear in the menu.  Then they can be removed from the menu but if they are saved on the notecard they will reproduce in the menu the next time the notecard loads.  What I don't get from Trot's description is how there might be bookmarks saved on the notecard that are not showing on the menu; or do they actually not show as removeable because they are saved on the notecard?

**Comment by Trotmistwalker** [comment] 2021-07-15 15:20
I realize that the scripts cannot delete from notecards and that is not what I am expecting.. I am expecting to still have the option of editing the settings as far as where the collar sends to a bookmark location regardless of what is on the .bookmarks note card. That is correct Silkie

**Comment by Trotmistwalker** [comment] 2021-07-15 15:25
one would think that one would be able to temporarily override what is on the .bookmarks note card until another .bookmarks is loaded with an update.. such as in the case of one of the locations has changed. Also there is the point that the bookmarks are still showing on the .settings print out until the collar scripts are reset.

**Comment by SilkieSabra** [comment] 2021-07-15 16:16
What I want to make sure about is if the bookmark is edited out of the notecard and the notecard is saved and loaded, does that bookmark get orphaned, as in still present in the list of bookmarks (because of being retained in script memory) and still not present in the Remove dialog?  Could this happen if the bookmark was added only to the notecard and then loaded, or if it was first added in the menu and then to the notecard?  This is not the same issue Trot is asking about.  I don't know if a temporary override feature is possible or advisable.

**Comment by Medea-Destiny** [comment] 2021-07-16 18:02
the .bookmarks destinations are read from the notecard as soon as the .bookmarks notecard is edited and saved, or every time the collar is attached (including while worn at log-in). The whole point of the .bookmarks notecard is to store landmarks that are non-volatile, while the remove button is to remove volatile ones. This could certainly be clarified in the menu text.

The volatile bookmarks are stored in oc_settings and restored from there on bootup, while non-volatile bookmarks are read directly from the notecard. The remove menu lists those volatile landmarks stored in settings and will remove them from settings storage permanently - unless someone has dumped their settings into the .settings notecard including those supposedly volatile  settings, in which case they will be restored when the .settings notecard gets read. As of 8.1 the dump of settings now has a warning about this.

My initial instinct was to hide the bookmark settings from the settings dump rather than just warning, but I didn't want to make that change for 8.1 without further consulting and there wasn't time to do that for 8.1. Thinking about this further I'm inclined to suggest that given the bookmark app's relatively stand-alone nature, the smart thing to do might be to do a bit of a rewrite of oc_bookmarks to exclude it from the boot-up reset process altogether and store the volatile settings solely in oc_bookmarks rather than sending them to oc_settings to be stored. This would avoid confusion with settings dumps and the .settings notecard , and would provide a small speed up and reduce script load on the boot-up process. Additionally we might include the non-volatile bookmarks in the remove menu with an asterisk in front of their names and explain in the remove menu's text (and as a response to attempting to click on one of those buttons) that these bookmarks need to be deleted from the .bookmarks notecard to remove them.

**Comment by SilkieSabra** [comment] 2021-07-16 20:30
I like the idea of reducing confusion and improving economy by segregating bookmarks from settings.  Other than that it seems to me that the bookmarks is functioning according to specs.  We tested bookmarks several ways and they do not appear in the Remove menu if they were saved in the bookmarks notecard, but a relog or reboot after editing them out of the notecard clears them.  Let's close this and reopen a feature request for V 8.2

**Closed by SilkieSabra** 2021-07-16 20:30 UTC
Labels: Refactoring, Waiting for reply
