### ISSUE TITLE
Constant script CPU usage while locked after adding 'oc_attachment_plugin'

### ISSUE THREAD

**Issue by Tynach** [OpenCollarTeam/OpenCollar#332] opened 2020-05-12 04:52 UTC
**What version of OpenCollar are you using?**
7.5, with oc_attachment_plugin installed.

**What behavior did you expect?**
CPU time to not increase while the collar is locked and not being interacted with.

**What behavior did you see instead?**
While the collar is locked, CPU time increases constantly despite the lack of any interaction.

**What steps does someone need to take to reproduce the problem?**
Install the `oc_attachment_plugin` app (for interacting with cuffs and other attachments), lock the collar, and repeatedly right-click the root prim and then click 'Script Info' to check the object's CPU time. It will steadily increase.

Unlocking the collar causes CPU time to slowly decrease. I'm fairly sure 'CPU time' is counted over a number of seconds or minutes, so as time goes on the amount of CPU time within that window of time should decrease unless the collar is interacted with.

If I interact with the collar by browsing menus, CPU time increases even while unlocked. This is expected and normal. But what is not expected is for CPU time to increase even without menus being browsed, and with nobody clicking the collar. Thankfully this only happens while the collar is locked, but many people prefer to always be locked, so this is potentially a big problem.

While locked, collar menus are also a bit slower to come up. I presume this is because of whatever is running constantly (infinite loop?) and causing CPU time to continually increase, but I can't say that with certainty.

I obtained `oc_attachment_plugin` from ZeCollar, but have run it along with [the copy here][lsl] through Kompare (a front-end to `diff`) and the two are identical.

Below is a log of the 'Script Info' events, as well as when the collar was locked/unlocked. a stock copy of OpenCollar 7.5 was used, except that the oc_attachment_plugin 'app' was installed.

```
[21:27:53] Script info: 'OpenCollar': [24/24] running scripts, 1536 KB allowed memory size limit, 0.197239 ms of CPU time consumed.
[21:27:58] Script info: 'OpenCollar': [24/24] running scripts, 1536 KB allowed memory size limit, 0.176978 ms of CPU time consumed.
[21:28:01] Script info: 'OpenCollar': [24/24] running scripts, 1536 KB allowed memory size limit, 0.165576 ms of CPU time consumed.
[21:28:03] Script info: 'OpenCollar': [24/24] running scripts, 1536 KB allowed memory size limit, 0.157470 ms of CPU time consumed.
[21:28:14] OpenCollar: Tynach (tynach.drascol)'s collar has been locked.
[21:28:19] Script info: 'OpenCollar': [24/24] running scripts, 1536 KB allowed memory size limit, 0.144103 ms of CPU time consumed.
[21:28:23] Script info: 'OpenCollar': [24/24] running scripts, 1536 KB allowed memory size limit, 0.150345 ms of CPU time consumed.
[21:28:27] Script info: 'OpenCollar': [24/24] running scripts, 1536 KB allowed memory size limit, 0.154230 ms of CPU time consumed.
[21:28:30] Script info: 'OpenCollar': [24/24] running scripts, 1536 KB allowed memory size limit, 0.156471 ms of CPU time consumed.
[21:28:33] Script info: 'OpenCollar': [24/24] running scripts, 1536 KB allowed memory size limit, 0.158084 ms of CPU time consumed.
[21:28:36] Script info: 'OpenCollar': [24/24] running scripts, 1536 KB allowed memory size limit, 0.159443 ms of CPU time consumed.
[21:28:41] OpenCollar: Tynach (tynach.drascol)'s collar has been unlocked.
[21:28:47] Script info: 'OpenCollar': [24/24] running scripts, 1536 KB allowed memory size limit, 0.158604 ms of CPU time consumed.
[21:28:50] Script info: 'OpenCollar': [24/24] running scripts, 1536 KB allowed memory size limit, 0.153216 ms of CPU time consumed.
[21:28:54] Script info: 'OpenCollar': [24/24] running scripts, 1536 KB allowed memory size limit, 0.148775 ms of CPU time consumed.
[21:28:57] Script info: 'OpenCollar': [24/24] running scripts, 1536 KB allowed memory size limit, 0.144770 ms of CPU time consumed.
[21:29:00] Script info: 'OpenCollar': [24/24] running scripts, 1536 KB allowed memory size limit, 0.141135 ms of CPU time consumed.
[21:29:02] Script info: 'OpenCollar': [24/24] running scripts, 1536 KB allowed memory size limit, 0.138918 ms of CPU time consumed.
[21:29:04] Script info: 'OpenCollar': [24/24] running scripts, 1536 KB allowed memory size limit, 0.136682 ms of CPU time consumed.
```

[lsl]: https://github.com/OpenCollarTeam/OpenCollar/blob/master/src/cuffs/collar/oc_attachment_plugin.lsl

**Comment by zontreck** [comment] 2020-05-12 05:02
I'm going to close this ticket, as spamming events intentionally to the scripts will always result in a slight increase in script time. Further, i do not see anything there of concern. The stats look normal to me, and this is not a bug

**Closed by zontreck** 2020-05-12 05:02 UTC

**Comment by zontreck** [comment] 2020-05-12 05:03
If you can point out a actual bug code wise or something the collar is doing and can link the CPU increase to it directly, this can be reopened as a bug. But as it stands this is not a bug

**Comment by Tynach** [comment] 2020-05-12 05:06
@zontreck, checking script info does not send events to the script. Even if it did, that would not explain the CPU time *only increasing while the collar is locked*. Instead, it would have the CPU time increase regardless of whether the collar was locked or not.
