### ISSUE TITLE
OCRC4 - BELL Sounds missing

### ISSUE THREAD

**Issue by AndurFaulds** [OpenCollarTeam/OpenCollar#475] opened 2021-01-19 01:55 UTC
What version of OpenCollar are you using? RC4

What behavior did you expect? BELL sounds

What behavior did you see instead? Bell sounds play only on sound options 5-8. Sound options 1-4 appear to trying to function but there is no sound. Volumes Change. Sounds Change. On/Off status changes. Other functions seem to be normal.

What steps does someone need to take to reproduce the problem? Cycle NEXT SOUND Option in the Bell Menu.

**Comment by zontreck** [comment] 2021-01-19 01:56
Will look into it but those sound assets are by UUID only, we would need someone to contribute new sound assets.  If they no longer work as you say then those sound references will be removed from the script.

**Comment by AndurFaulds** [comment] 2021-01-19 01:59
Re-Verified. It's 1-3 not working

**Comment by zontreck** [comment] 2021-01-19 02:00
Thank you will check. As i said though they will likely just be removed if they are not working at all

**Comment by SilkieSabra** [comment] 2021-01-19 02:01
why do we have so many different bell sounds anyway

**Comment by zontreck** [comment] 2021-01-19 02:02
dunno. good question

**Comment by zontreck** [comment] 2021-01-19 08:31
All sounds work, some are simply quieter than others. @AndurFaulds this should perhaps be modified to a request for updated bell sounds, though still something that is not easily handled. I can do scripts, mesh, and animations, but sounds and textures are out of my scope of expertise.

**Comment by zontreck** [comment] 2021-01-22 05:49
Closing as unable to reproduce

**Closed by zontreck** 2021-01-22 05:49 UTC
Labels: 8.0, PRIORITY 3, Waiting for reply
