### ISSUE TITLE
Titler permissions are reversed for Self-Owned and Trusted

### ISSUE THREAD

**Issue by mistressohm** [OpenCollarTeam/OpenCollar#207] opened 2019-04-23 15:29 UTC
What version of OpenCollar are you using?  7.1

What behavior did you expect?  Self Owned should be able to reset/change Titler settings after Trusted sets a title

What behavior did you see instead?  [08:16] Madame Beatrice: You currently have not the right to change the Titler settings, someone with a higher rank set it!

What steps does someone need to take to reproduce the problem?  Have a Trusted person set a title on a collar that is Self-Owned.  Then have Self-Owner try to reset it or change it.

Added info: 
[08:16] Madame Beatrice: Owners: 
Beatrice McAllister (mistressohm)
[08:16] Madame Beatrice: Trusted: 
Susanne (susanne23)
Octavia Sorbet
MelodyFoxx
Kin Feltail (kin.flagon)
[08:16] Madame Beatrice: Blocked: 
Pandora Vintersorg (goddessceska)
[08:16] Madame Beatrice: Public Access: closed

**Comment by mistressohm** [comment] 2019-04-23 16:02
Looks like issue was in oc_auth, rezzing collar and resetting the scripts cleared the title, whereas resetting oc_titler only did not.

**Comment by mistressohm** [comment] 2019-04-23 16:14
oc_auth reset (cleared the access list, boo!)  and problem no longer evident.

Further research - are other apps equally affected when this happens?  Why would oc_auth need a reset with 6 slots used (self-owned, 4 trusted, 1 block)?

**Comment by zontreck** [comment] 2019-04-24 04:36
Hi just a quick guess without doing any research into the particular issue is that it may be that if any owner, trusted, etc is set, then unless you have ownself enabled, you would be denied being able to change the title. I'll look saving the authority from last change, and having it check for access that way

**Comment by zontreck** [comment] 2019-04-24 04:41
I was mostly right. It appears that the titler is caching the last authority level, so when owner or trusted change the title it'll lock out the wearer. I'm fixing this right now, will have a patch up momentarily

**Comment by zontreck** [comment] 2019-04-24 05:13
Issue verified. Fixing it

**Comment by zontreck** [comment] 2019-04-24 05:38
@mistressohm I was only able to verify that after wearer sets a new title, that trusted cannot set the title anymore due to ownself setting wearer as a higher authority level.   I am still trying to reproduce the exact bug that you mention above. Also i am not sure why resetting oc_auth would have fixed anything unless it had stack heaped as the settings are stored under oc_settings, including the owners list.

**Comment by SilkieSabra** [comment] 2019-04-24 12:44
I helped with this problem.  The titler appeared to be stuck returning the message "You cannot change the title because someone with a higher rank than you set it."  This happened to the wearer even when she had OwnSelf checked, which should have given her owner access to the titler.  We tested it adding me first to trusted and then to owner.  Even with me set to owner the same message was returned. Resetting the titler script did not fix the issue, but resetting the entire collar did.  From this I guessed that the problem might have been in auth, although otherwise auth was working.

The expected behavior for this app is that Owners including Ownself, and Trusted can set the title,  and if an Owner has set the title, Trusted, Group, and Public access cannot change it.

**Comment by mistressohm** [comment] 2019-04-24 13:57
Thanks for your attention on this.   If you were able to reproduce the problem (Silkie and I could not,  once collar scripts were reset) and have traced it to cached data, then this might affect other apps.  Based on my RW experience with auth issues (streaming video platforms) a best practice is to assign a TTL value to any cached credentials, so that even if a cache gets stuck, a TTL check will force a reload of creds from source because they're simply too old.  This wouldn't fix issues with "immediate" changes, but would solve them fairly well with a little patience on the user's part.  UNIX epoch time + 5 min would be my suggestion.

**Comment by zontreck** [comment] 2019-04-24 20:53
I couldn't reproduce this issue though but if you know what caused it to get stuck i should be able to get it to happen. Was it changing the owner authority level that caused it?

**Comment by mistressohm** [comment] 2019-04-24 20:57
I can't say.  I did add a Trusted name to the access list, and I believe
she changed the title soon after that (within an hour).

**Comment by zontreck** [comment] 2019-04-24 21:49
hmm.. Well, the only thing i can see which might be confusing for some- Is that after self-owned wearer changes the title, trusted will be unable to change it anymore, but owner can.

**Comment by zontreck** [comment] 2019-04-24 21:50
Also can you reply with the titler script version please? And is it signed with the OpenCollar experience?

**Comment by zontreck** [comment] 2019-04-25 01:37
Cannot reproduce the issue. Closing the ticket. If the issue returns or you have a better idea of how to reproduce this issue, please either reopen this ticket or submit a new one

**Closed by zontreck** 2019-04-25 01:37 UTC
Labels: Bug, More Info Needed
