### ISSUE TITLE
Missing Unsit Chat Command

### ISSUE THREAD

**Issue by SilkieSabra** [OpenCollarTeam/OpenCollar#761] opened 2022-03-28 17:51 UTC
There should be a chat command to unsit.  Either it wasn't updated/changed to unsit  or it got lost.  There used to be a standnow chat command.  Tried that and also stand.  Neither worked.  Have not tried to locate it in the script but it's not functioning in at least two collars tested.

**Comment by Medea-Destiny** [comment] 2022-04-21 00:25
Duplicate of #703 -- fix is already merged.

**Closed by Medea-Destiny** 2022-04-21 00:25 UTC
Labels: Bug, 8.3, Needs testing
