### ISSUE TITLE
Unsit chat command not working

### ISSUE THREAD

**Issue by vacant-stare** [OpenCollarTeam/OpenCollar#799] opened 2022-05-26 23:35 UTC
What version of OpenCollar are you using? 8.2.1

What behavior did you expect? vaunsit should unsit me

What behavior did you see instead? vaunsit DID NOT unsit me

What steps does someone need to take to reproduce the problem? sit, try and unsit using [prefix]unsit (as documented on Opencollar.cc

**Comment by pfifo** [comment] 2022-07-13 03:52
its vastand
unsit is the RLV command

**Comment by tayaphidoux** [comment] 2022-07-15 21:44
@Vacant-stare vastand as mentioned by @pfifo is correct however it seems unsit is more natural even my owner calls it before correcting their command to get me off of things.

**Comment by Medea-Destiny** [comment] 2022-08-01 21:20
duplicate of #703, fix will be in 8.2.2

**Closed by Medea-Destiny** 2022-08-01 21:20 UTC
