### ISSUE TITLE
Restrictions Menu Creation broke

### ISSUE THREAD

**Issue by OneWithoutAName** [OpenCollarTeam/OpenCollar#723] opened 2022-01-19 17:04 UTC
What version of OpenCollar are you using?
8.2.1
What behavior did you expect?
Menu sytem to work
What behavior did you see instead?
Menu broken (rlv restrictions creating custom sets)
What steps does someone need to take to reproduce the problem?
Try to delete a restriction set and create a new one.  It saves as the bitmask not the name and does not run

**Comment by Medea-Destiny** [comment] 2022-02-01 23:05
Thanks for the bug report. Issue indeed will only occur if you delete all presets, and is caused by an emptied list of presets being saved to settings and then restored as a list with a single blank entry, which puts all subsequent additions to the list out of stride (button name and mask values appear in the wrong locations in the list.)

#738 provides a fix for this issue. In the meanwhile anyone encountering this problem, you can restore the original presets from the customize menu, and I suggest not deleting all presets until the next OC release, with the fix in place.

**Closed** 2023-08-05 16:53 UTC
